apiVersion: v1
kind: Service
metadata:
  name: paperless-worker
  labels:
    app: paperless-worker
spec:
  selector:
    app: paperless-worker
  ports:
    - name: http
      port: 8084
      targetPort: 8084
